/* ANDREW WILL CREATE SOME QUERIES HERE BASED ON THE NOTES IN THE GEARSS DATA DICTIONARY 

1. COUNT OF ALL UNIQUE SOURCE AND STANDARD CONCEPT PAIRS ALL SOURCE FOR ED VISITS (INCLUDING STRINGS)

2. COUNTS OF GEARS CONCEPTS IN CONDITION, MEASUREMENT, AND OBSERVATION TABLES FOR ED VISITS (JOIN ON CONCEPT CODES FROM ATHENA THAT ANALYSTS LOOKUP)

3. GENERATE DATA-ELEMENT SPECIFIC QUERIES USING "SPECIFICATIONS FOR QUERY" TAB IN gearss_data_dictionary_wOMOP.XLSX FILE

*/
